### ISSUE TITLE
age_group kulcsban space

### ISSUE THREAD

**Issue by connorhu** [baueri/kozossegek-hu#18]
Tegnap a miserendhez írtam új klienst és akkor fedeztem fel, hogy space van az age_group kulcs végén.
https://github.com/baueri/kozossegek-hu/blob/dbaddad14db45d15289cf780fe81b8327977f725/app/Portal/Controllers/Api/V1/ApiGroupController.php#L76

**Comment by connorhu** [comment]
Szerintem a json_decode alap beállításokkal nem érzékeny a space-re, ezért nem tűnt fel senkinek Ha nagyon alapos akarsz lenni akkor csak duplikálod, javítod és majd egy következő API verzióban vezeted ki.

**Comment by baueri** [comment]
Annyira szerintem nem használják sokan az api-t, hogy emiatt külön verziót váltsak :)

btw javítva.
